export const Jeans = {
  dama: [
    {
      name: "Arenado gris elastizado",
      src: "/products/dama-arenado-gris-elastizado-36a46.png",
      talles: "36 a 46",
      text: "Jean dama Arenado gris elastizado",
      precio: 3899,
    },
    {
      name: "Engomado tostado",
      src: "/products/engomado-tostado-36a46.png",
      talles: "36 a 46",
      text: "Pantalón dama Engomado tostado",
      precio: 3999,
    },
    {
      name: "Negro elastizado con vista",
      src: "/products/dama-negro-elastizado-vista-36a46.png",
      talles: "36 a 46",
      text: "Jean dama negro elastizado con vista",
      precio: 3899,
    },
    {
      name: "Hilo blanco elastizado",
      src: "/products/negro-hilo-blanco-erlastizado-36a46.png",
      talles: "36 al 46",
      text: "Jean dama negro hilo blanco elastizado",
      precio: 3899,
    },
    {
      name: "Hilo blanco c/vista",
      src: "/products/dama-vista-hilo-blanco-36a46.png",
      talles: "36 al 46",
      text: "Jean dama negro hilo blanco c/vista",
      precio: 3899,
    },
    {
      name: "Dama elastizado",
      src: "/products/dama-elastizado-36a46.png",
      talles: "36 al 46",
      text: "Jean dama Hilo blanco elastizado",
      precio: 3899,
    },
    {
      name: "Elastizado tiro alto c/bolsillo",
      src: "/products/dama-elastizado-tiroalto-bolsillo-36a46.png",
      talles: "36 al 46",
      text: "Jean dama Elastizado tiro alto c/bolsillo",
      precio: 3899,
    },
    {
      name: "Elastizado c/bolsillo",
      src: "/products/dama-elastizadobolsillovista-36a46-2.png",
      talles: "36 a 46",
      text: "Jean elastizado con bolsillo a la vsita",
      precio: 3599,
    },
    {
      name: "Elastizado nevado c/bolsillo",
      src: "/products/dama-bolsillo-vista-elastizado-nevado-36a46.png",
      talles: "36 a 46. Solo x curva.",
      text: "Jean dama Elastizado nevado c/bolsillo a la vista",
      precio: 3599,
    },
    {
      name: "Cargo negro rígido",
      src: "/products/dama-cargo-negro-rigido-36a46.png",
      talles: "36 a 46",
      text: "Jean dama Cargo negro rígido",
      precio: 5199,
    },
    {
      name: "Económico elastizado",
      src: "/products/dama-economico-elastizado-36a46.png",
      talles: "36 a 46. Solo x curva.",
      text: "Jean dama Económico elastizado",
      precio: 3299,
    },
    {
      name: "Azul elastizado Con vista",
      src: "/products/dama-vista-azul-elastizado-36a46.png",
      talles: "36 a 46.",
      text: "Jean dama Azul elastizado Con vista",
      precio: 3699,
    },
    {
      name: "Mom negro rígido",
      src: "/products/dama-mom-negro-rigido-36a46.png",
      talles: "36 a 46",
      text: "Jean dama Mom negro rígido",
      precio: 4499,
    },
    {
      name: "Jean Gris c/bolsillo",
      src: "/products/dama-grisbolsillo-36a46.png",
      talles: "36 a 46",
      text: "Jean Gris c/bolsillo",
      precio: 3699,
    },
    {
      name: "Locas Arenado azul",
      src: "/products/dama-locas-arenado-azul-36a46.png",
      talles: "36 a 46",
      text: "Jean dama 'Locas' AArenado azul",
      precio: 4399,
    },
    {
      name: "Engomado negro elastizado",
      src: "/products/dama-engomado-negro-elastizado-36a46.png",
      talles: "36 a 46",
      text: "Jean dama Engomado negro elastizado",
      precio: 3999,
    },
    {
      name: "Oxford arenado elastizado",
      src: "/products/dama-oxford-arenado-elastizado-38a48.png",
      talles: "38 a 48",
      text: "Jean dama Oxford arenado elastizado",
      precio: 4099,
    },
    {
      name: "Jean Elastizado Azul",
      src: "/products/dama-azul-36a46.png",
      talles: "36 a 46",
      text: "Jean Gris c/bolsillo",
      precio: 2999,
    },
    {
      name: "Elastizado con rotura",
      src: "/products/dama-elastizadorotura-36.sq.png",
      talles: "solo 36",
      text: "Jean elastizado con roturas, solo talle 36",
      precio: 2999,
    },
    {
      name: "Cargo Wide Leg",
      src: "/products/dama-cargo-wide-leg-36a46-curva.png",
      talles: "36 al 46. Solo x curva.",
      text: "Jean Cargo Wide Leg con roturas",
      precio: 5399,
    },
    // {
    //   name: "Jean: Las Locas",
    //   src: "/products/dama-laslocas-40a46-sq.png",
    //   talles: "40 al 46",
    //   text: "Jean Las Locas",
    //   precio: 4199,
    // },

    {
      name: "Jean Negro c/bolsillo",
      src: "/products/dama-negrobolsillo-36a46.png",
      talles: "36 al 46",
      text: "Jean negro de dama con bolsillos",
      precio: 3899,
    },
    {
      name: "Nevado oscuro elastizado c/bolsillo",
      src: "/products/dama-nevado-oscuro-elastizado-bolsillo-36a46.png",
      talles: "36 al 46",
      text: "Jean dama Nevado oscuro elastizado c/bolsillo",
      precio: 3899,
    },
    // {
    //   name: "Las Locas (Gris)",
    //   src: "/products/dama-locas-gris-36a46-sq.png",
    //   talles: "36 al 46",
    //   text: "Jean Las Locas - Gris",
    //   precio: 4199,
    // },
    {
      name: "Jean nevado",
      src: "/products/dama-nevado-elastizado-sq.png",
      talles: "36 al 46",
      text: "Jean nevado elastizado",
      precio: 3199,
    },
    {
      name: "Jean celeste localizado",
      src: "/products/dama-celestelocalizado-36a46.png",
      talles: "36 al 46",
      text: "Jean nevado elastizado",
      precio: 2999,
    },
    {
      name: "Talle especial elastizado",
      src: "/products/mujer-especial-elastizado-48a56.png",
      talles: "48 al 56",
      text: "Jean dama especial elastizado",
      precio: 4499,
    },
    {
      name: "Talle especial negro elastizado",
      src: "/products/dama-especial-negro-elastizado-48a56.png",
      talles: "48 al 56",
      text: "Jean dama especial negro elastizado",
      precio: 4699,
    },
    {
      name: "Jean Oxfordd",
      src: "/products/dama-oxford-38a48.png",
      talles: "38 al 48. Agotado.",
      text: "Jean Oxfordd de dama",
      precio: 0,
    },
  ],
  hombre: [
    {
      name: "Localizado azúl semichupín",
      src: "/products/hombre-localizado-azul-semichupin-40a48.png",
      talles: "40 al 48",
      text: "Jean hombre Localizado azúl semichupín",
      precio: 4199,
    },
    {
      name: "Negro elastizado",
      src: "/products/hombre-negro-elastizado-38a48.png",
      talles: "38 al 48",
      text: "Jean hombre Negro elastizado",
      precio: 4399,
    },
    {
      name: "Jogger gris rígido",
      src: "/products/hombre-jogger-gris-rigido-38a48-curva.png",
      talles: "40 al 48",
      text: "Jean hombre Jogger gris rígido",
      precio: 4999,
    },
    {
      name: "Azul hilo blanco semichupín",
      src: "/products/hombre-azul-hilo-blacno-semichupin-40a48.png",
      talles: "40 al 48",
      text: "Jean hombre Azul hilo blanco semichupín",
      precio: 4199,
    },
    {
      name: "Corte Chino negro",
      src: "/products/hombre-corte-chino-negro-38a48.png",
      talles: "38 al 48. Solo x curva.",
      text: "Jean hombre Corte Chino negro",
      precio: 4699,
    },
    {
      name: "Cargo Jogger",
      src: "/products/hombre-cargojogger-38a46-sq.png",
      talles: "38 al 46",
      text: "Jean Cargo Jogger de Hombre",
      precio: 5199,
    },
    {
      name: "Cargo Jogger Celeste",
      src: "/products/hombre-cargo-jogger-celeste-38a48.png",
      talles: "38 al 48",
      text: "Jean Cargo Jogger celeste de Hombre",
      precio: 5499,
    },

    {
      name: "Jogger rígido nevado roto",
      src: "/products/hombre-jogger-rigido-nevado-roto-38a48.png",
      talles: "38 al 48. Solo x curva.",
      text: "Jean Jogger rígido nevado roto",
      precio: 4999,
    },
    {
      name: "Jeans Talle Grande",
      src: "/products/hombre-grande-50a58.png",
      talles: "50 al 58",
      text: "Jeans de hombre, talles especiales",
      precio: 5299,
    },
    {
      name: "Clásico rígido",
      src: "/products/hombre-clasicorigido-42a52-sq.png",
      talles: "50 y 52",
      text: "Jean rígido clásico, dos tonos",
      precio: 5199,
    },
    {
      name: "Elastizado Talle Grande",
      src: "/products/hombre-elastizado-50a58-sq.png",
      talles: "50 al 58",
      text: "Talles grandes",
      precio: 5299,
    },
    {
      name: "Mom Rígido con roturas",
      src: "/products/hombre-momrigidoroturas-38a48-sq.png",
      talles: "38 al 48",
      text: "Mom rígido con roturas para hombre",
      precio: 4499,
    },
    {
      name: "Jogger rìgido con puño",
      src: "/products/hombre-jogger-rigido-puño-cargo-arenado-liso-38a48.png",
      talles: "38 al 48",
      text: "Jean hombre ogger rìgido con puño cargo arenado y liso",
      precio: 5499,
    },
    {
      name: "Rígido Liso",
      src: "/products/hombre-rigido-liso-42a52-sq.png",
      talles: "42 al 52",
      text: "Rígido liso de hombre",
      precio: 4799,
    },
  ],
  otros: [],
};
