export const Jeans = {
  dama: [
    {
      name: "Elastizado c/bolsillo",
      src: "/products/dama-elastizadobolsillovista-36a46-2.png",
      talles: "36 a 46",
      text: "Jean elastizado con bolsillo a la vsita",
      precio: 3599,
    },
    {
      name: "Jean Gris c/bolsillo",
      src: "/products/dama-grisbolsillo-36a46.png",
      talles: "36 a 46",
      text: "Jean Gris c/bolsillo",
      precio: 3699,
    },
    {
      name: "Jean Elastizado Azul",
      src: "/products/dama-azul-36a46.png",
      talles: "36 a 46",
      text: "Jean Gris c/bolsillo",
      precio: 2999,
    },
    {
      name: "Elastizado con rotura",
      src: "/products/dama-elastizadorotura-36.sq.png",
      talles: "solo 36",
      text: "Jean elastizado con roturas, solo talle 36",
      precio: 2999,
    },
    {
      name: "Jean: Las Locas",
      src: "/products/dama-laslocas-40a46-sq.png",
      talles: "40 al 46",
      text: "Jean Las Locas",
      precio: 4199,
    },
    {
      name: "Jean Oxfordd",
      src: "/products/dama-oxford-38a48.png",
      talles: "38 al 48",
      text: "Jean Oxfordd de dama",
      precio: 3899,
    },
    {
      name: "Jean Negro c/bolsillo",
      src: "/products/dama-negrobolsillo-36a46.png",
      talles: "36 al 46",
      text: "Jean negro de dama con bolsillos",
      precio: 3699,
    },
    {
      name: "Las Locas (Gris)",
      src: "/products/dama-locas-gris-36a46-sq.png",
      talles: "36 al 46",
      text: "Jean Las Locas - Gris",
      precio: 4199,
    },
    {
      name: "Jean nevado",
      src: "/products/dama-nevado-elastizado-sq.png",
      talles: "36 al 46",
      text: "Jean nevado elastizado",
      precio: 3199,
    },
    {
      name: "Jean celeste localizado",
      src: "/products/dama-celestelocalizado-36a46.png",
      talles: "36 al 46",
      text: "Jean nevado elastizado",
      precio: 2999,
    },
  ],
  hombre: [
    {
      name: "Cargo Jogger",
      src: "/products/hombre-cargojogger-38a46-sq.png",
      talles: "38 al 46",
      text: "Jean Cargo Jogger de Hombre",
      precio: 5199,
    },
    {
      name: "Jeans Talle Grande",
      src: "/products/hombre-grande-50a58.png",
      talles: "50 al 58",
      text: "Jeans de hombre, talles especiales",
      precio: 4999,
    },
    {
      name: "Clásico rígido",
      src: "/products/hombre-clasicorigido-42a52-sq.png",
      talles: "42 al 52",
      text: "Jean rígido clásico",
      precio: 4799,
    },
    {
      name: "Elastizado Talle Grande",
      src: "/products/hombre-elastizado-50a58-sq.png",
      talles: "50 al 58",
      text: "Talles grandes",
      precio: 4999,
    },
    {
      name: "Mom Rígido con roturas",
      src: "/products/hombre-momrigidoroturas-38a48-sq.png",
      talles: "38 al 48",
      text: "Mom rígido con roturas para hombre",
      precio: 4499,
    },
    {
      name: "Rígido Liso",
      src: "/products/hombre-rigido-liso-42a52-sq.png",
      talles: "38 al 48",
      text: "Mom con roturas para hombre",
      precio: 4799,
    },
  ],
  otros: [],
};
